### ISSUE TITLE
add link to github to final slide

### ISSUE THREAD

**Issue by brycepj** [brycepj/flexbox#10]

**Comment by dandv** [comment]
:+1: Had to look in the source code, then do a Whois, then a Google search to find this :)

**Comment by dandv** [comment]
Saw all my issues closed. Is the project no longer maintained?

**Comment by brycepj** [comment]
Yeah, sorry if that seemed a little abrupt. I refactored the whole app and assumed existing issues were no longer relevant. I probably should go back through and double check that.
